### ISSUE TITLE
Can't get functionality to work!

### ISSUE THREAD

**Issue by chrismaltais** [nikodraca/slackify#1]
I followed the install instructions, and the script seems to be running properly as seen by the follow video:

![Alt Text](http://g.recordit.co/mktsprwbC3.gif)

I've created a Slack token and added it to line 42 in `app.py`

However, I can't see the Spotify logo beside my name in Slack!

Let me know if you suspect any leads, until then I'll continue debugging and will let you know if I resolve the issue.

Cheers,
Chris

**Comment by chrismaltais** [comment]
Hey!

After playing around with it a bit, it turns out my Slack desktop app couldn't register the Spotify (:spotify:) emoji. Below is an example of it working with the musical notes (:notes:)

<img width="910" alt="screen shot 2018-04-11 at 12 51 41 am" src="https://user-images.githubusercontent.com/17098959/38597033-2e3eab7a-3d23-11e8-83bd-b5b2a68f921d.png">

Before we close the issue, it would be nice to know why this Spotify emoji issue is happening and how to resolve it. I'll look into it more tomorrow!

**Comment by nikodraca** [comment]
Hi Chris,

You'll need to add the custom Spotify emoji to your workplace before this can work. You could also use any other emoji by changing the profile dictionary (as you had done).

- Niko
